#! /usr/bin/env python3
# google_forms_data.py - Collects a list of email addresses from a Google Form

import logging
import ezsheets
import sys

logging.basicConfig(level=logging.DEBUG, format=' %(asctime)s - %(levelname)s - %(message)s')
#logging.disable(logging.DEBUG)

# Get a sheet id to open the worksheet
def get_sheet_id():
    sheet_name = sys.argv[1]
    sheets = ezsheets.listSpreadsheets()
    for sheet_id in sheets:
        if sheet_name not in sheets.values():
            return Exception('This worksheet was not found in Google Drive')
        if sheets[sheet_id] == sheet_name:
            logging.debug(sheet_id)
            return sheet_id

# Get a list of e-mail addresses from the spreadsheet
def get_email_addresses(sheet_id):
    spreadsheet = ezsheets.Spreadsheet(sheet_id)
    logging.debug(spreadsheet.title)
    # Working with the 'active' sheet as the spreadsheet generated by the form will only have 1 sheet
    sheet = spreadsheet[0]
    columns = sheet.getColumns()
    email_addresses = []
    for column, cells in enumerate(columns):
        for cell in cells:
            if '@' in cell:
                email_addresses.append(cell)
    logging.debug(email_addresses)
    return email_addresses
    #a = [cell for cell in columns[2] if '@' in cell]
        
def main():
    sheet_id = get_sheet_id()
    get_email_addresses(sheet_id)

if __name__ == '__main__':
    main()