print("Enter the first number to add:")
first = int(input())
print("Enter the second number to add:")
second = int(input())
print("Enter the third number to add:")
third = int(input())
print(f"The sum is {first + second + third}")
